package com.nzy.miaosha.dao;

import com.nzy.miaosha.entity.Password;

public interface PasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Mon Jun 17 11:12:04 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Mon Jun 17 11:12:04 GMT+08:00 2019
     */
    int insert(Password record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Mon Jun 17 11:12:04 GMT+08:00 2019
     */
    int insertSelective(Password record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Mon Jun 17 11:12:04 GMT+08:00 2019
     */
    Password selectByPrimaryKey(Integer id);

    Password selectByUserId(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Mon Jun 17 11:12:04 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Password record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Mon Jun 17 11:12:04 GMT+08:00 2019
     */
    int updateByPrimaryKey(Password record);
}